const fs=require('fs'),vm=require('vm'),assert=require('assert'),cp=require('child_process'),path=require('path');
const root=path.resolve(__dirname,'..');
function wrap(n){if(typeof n==='string')return n;const children=n.children.map(wrap);const descendants=()=>children.filter(c=>typeof c!=='string').flatMap(c=>[c,...c.descendants()]);return {tag:n.tag,attrs:n.attrs,children:children.filter(c=>typeof c!=='string'),descendants,textContent:children.map(c=>typeof c==='string'?c:c.textContent).join(''),value:n.attrs.value,getAttribute:k=>n.attrs[k]??null,querySelector(s){return this.querySelectorAll(s)[0]||null},querySelectorAll(s){const match=(c,s)=>{let tag=s.match(/^[a-z]+/)?.[0];let id=s.match(/#([\w-]+)/)?.[1];let cl=s.match(/\.([\w-]+)/)?.[1];let attr=s.match(/\[([^=\]]+)(?:="([^"]*)")?\]/);return (!tag||c.tag===tag)&&(!id||c.attrs.id===id)&&(!cl||(c.attrs.class||'').split(' ').includes(cl))&&(!attr||(attr[2]!==undefined?c.attrs[attr[1]]===attr[2]:attr[1] in c.attrs));};if(s.includes(' > ')){const [a,b]=s.split(' > ');return this.querySelectorAll(a).flatMap(c=>c.children.filter(x=>match(x,b)));}if(s.includes(' ')){const [a,...rest]=s.split(' ');return this.querySelectorAll(a).flatMap(c=>c.querySelectorAll(rest.join(' ')));}return descendants().filter(c=>match(c,s));}}}
(async()=>{
const raw=cp.execFileSync('python',[path.join(__dirname,'extract_fixture.py'),process.argv[2]],{maxBuffer:4000000,encoding:'utf8'});const doc=wrap(JSON.parse(raw));const parserContext={};vm.createContext(parserContext);vm.runInContext(fs.readFileSync(root+'/common/parser.js','utf8'),parserContext);const parse=parserContext.MoeParser.parse;const snapshot=JSON.parse(JSON.stringify(parse(doc)));assert.equal(snapshot.account,'サンプル倉庫A');assert.equal(snapshot.items.length,124);assert.equal(snapshot.items.reduce((s,i)=>s+i.quantity,0),3486);assert(snapshot.items.some(i=>i.name==='サマーラッキーバッグ 2026 [ K ]'));console.log('PASS attached HTML: account, rows, total, full title');
const input=doc.querySelector('[name="PAGE_CURRENT"]');input.value='2';assert.equal(parse(doc).page,2);input.value='bad';assert.throws(()=>parse(doc));input.value='1';const tbody=doc.querySelector('table.gridlayout').querySelector('tbody');tbody.children.pop();assert.throws(()=>parse(doc));console.log('PASS page identification and incomplete-page rejection');
let listener;let db={};const api={runtime:{getURL:()=> 'moz-extension://test/',onMessage:{addListener:f=>listener=f}},storage:{local:{get:async()=>structuredClone(db),set:async d=>{db=structuredClone(d)}}}};const ctx={browser:api,console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/common/background.js','utf8'),ctx);const sender={url:'https://moepic.com/mp_itembox/mp_itembox.php'};const ext={url:'moz-extension://test/popup.html'};const send=(m,s=sender)=>new Promise(r=>listener(m,s,r));
await Promise.all([send({type:'capture',snapshot}),send({type:'capture',snapshot:{...snapshot,page:2}})]);assert.equal(Object.keys(db.ledger.accounts[0].pages).length,2);await send({type:'capture',snapshot});assert.equal(db.ledger.accounts.length,1);assert.equal(db.ledger.accounts[0].pages[1].items.length,124);console.log('PASS parallel capture, per-page isolation, no duplicates');
await send({type:'register',account:snapshot.account,loginId:'example'});assert.equal(db.ledger.accounts[0].loginId,'example');assert.equal((await send({type:'capture',snapshot})).fresh,false);await send({type:'capture',snapshot:{...snapshot,account:'Test B'}});assert.equal(db.ledger.accounts.length,2);console.log('PASS registration and multiple accounts');
await send({type:'auto',value:false},ext);assert((await send({type:'capture',automatic:true,snapshot})).disabled);const backup=structuredClone(db.ledger);assert((await send({type:'restore',ledger:{bad:true}},ext)).error);assert.deepEqual(db.ledger,backup);assert((await send({type:'restore',ledger:backup},ext)).ok);assert((await send({type:'capture',snapshot},{url:'https://example.com'})).error);console.log('PASS auto-off, backup validation/restore, sender checks');
})().catch(e=>{console.error(e);process.exit(1)});
